# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafreezer', '0002_dataset_has_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='datadictionaryfield',
            options={'verbose_name': 'data dictionary field', 'verbose_name_plural': 'data dictionary fields'},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='could_parse',
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(to='datafreezer.Tag'),
        ),
    ]
