# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafreezer', '0008_auto_20160818_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_file',
            field=models.FileField(max_length=500, upload_to=b'/Users/Tyler/Documents/Work/DMN/Development/cold-data-storage/django-datafreezer/datafreezer/uploads/%Y/%m/%d/'),
        ),
    ]
