# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafreezer', '0011_auto_20160818_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_file',
            field=models.FileField(max_length=500, upload_to=b'%Y/%m/%d/'),
        ),
    ]
