# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datafreezer', '0014_dataset_source_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionaryfield',
            name='parent_dict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datafreezer.DataDictionary'),
        ),
    ]
