# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafreezer', '0015_auto_20160824_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionaryfield',
            name='dataType',
            field=models.CharField(choices=[(b'INTEGER', b'Integer'), (b'FLOAT', b'Decimal'), (b'TEXT', b'Text'), (b'LONGTEXT', b'Longtext'), (b'DATE', b'Date'), (b'TIME', b'Time'), (b'DATETIME', b'Datetime')], default=b'TEXT', max_length=10),
        ),
    ]
